/*
	Script d'importation du fichier CSV : ADHERENTS.csv
    - Création de la table des adhérents
*/
DROP TABLE IF EXISTS public.ADHERENTS ;
CREATE TABLE  public.ADHERENTS  (
  "NUMADHER" integer NOT NULL PRIMARY KEY,
  "NOM1" text DEFAULT NULL,
  "NOM2" text DEFAULT NULL,
  "ADR1" text DEFAULT NULL,
  "ADR2" text DEFAULT NULL,
  "CP" character(5) DEFAULT NULL,
  "VILLE" text DEFAULT NULL,
  "DEP" character(2) DEFAULT NULL ,
  "LIBDEP" text DEFAULT NULL,
  "LIBREG" text DEFAULT NULL,
  "CODE_INDUSTRIE" character(2) DEFAULT NULL REFERENCES corr_industrie,    
  "LIBELLE_INDUSTRIE" text DEFAULT NULL,
  "SIRET" character(14) DEFAULT NULL,
  "CIVIL1" text DEFAULT NULL,
  "CIVIL2" text DEFAULT NULL,
  "CORRES1" text DEFAULT NULL,
  "CORRES2" text DEFAULT NULL,
  "TEL1" character(10) DEFAULT NULL,
  "TEL2" character(10) DEFAULT NULL,
  "PANEL" character(1) DEFAULT NULL,
  "EMAIL" text DEFAULT NULL,
  "EMAIL2" text DEFAULT NULL,
  "FAX" character(10) DEFAULT NULL,
  "SITE_WEB" text DEFAULT NULL,
  "COMMENTAIRE" text DEFAULT NULL,
  "DT_CRE" text DEFAULT NULL,
  "DT_SUPPR" text DEFAULT NULL,
  "DT_REACTIV" text DEFAULT NULL
) ;

copy public.ADHERENTS ("NUMADHER", "NOM1", "NOM2", "ADR1", "ADR2", "CP", "VILLE", "DEP", "CODE_INDUSTRIE", "SIRET", "CIVIL1", "CIVIL2", "CORRES1", "CORRES2", "TEL1", "TEL2", "PANEL", "EMAIL", "EMAIL2", "FAX", "SITE_WEB", "COMMENTAIRE", "DT_CRE", "DT_SUPPR", "DT_REACTIV") 
FROM '/data/nodejs/dev/cnc/ADHERENTS.csv' DELIMITER ';' CSV HEADER ENCODING 'LATIN9' QUOTE '"' ESCAPE '''';